version: '3.8'
services:
  mongodb:
    image: mongo:5.0.15
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
  bot:
    build:
      context: .
    depends_on:
      - mongodb
    env_file:
      - .env.prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
